# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2020-12-11 13:18:25
"""
import arcpy
from sys import argv

def Model(Dissolve_Field_s_=["UID_AE2S", "HK", "InitSoilMo", "CapSuction"], Dissolve_Field_s_2_=["UID_AE2S", "Perc_Imp"]):  # RHSubcatchment

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False

    RiverHills_AE2S = "RiverHills_AE2S"
    RiverHillsSoilsData = "RiverHillsSoilsData"
    RiverHillsImpervious = "RiverHillsImpervious"

    # Process: Intersect (2) (Intersect) (analysis)
    soilmu_a_aoi_Intersect = "C:\\Users\\TMcStraw\\Documents\\ArcGIS\\Default.gdb\\soilmu_a_aoi_Intersect"
    arcpy.analysis.Intersect(in_features=[[RiverHills_AE2S, ""], [RiverHillsSoilsData, ""]], out_feature_class=soilmu_a_aoi_Intersect, join_attributes="ALL", cluster_tolerance="", output_type="INPUT")

    # Process: Dissolve (2) (Dissolve) (management)
    soilmu_a_aoi_Intersect_Disso = "C:\\Users\\TMcStraw\\Documents\\ArcGIS\\Default.gdb\\soilmu_a_aoi_Intersect_Disso"
    arcpy.management.Dissolve(in_features=soilmu_a_aoi_Intersect, out_feature_class=soilmu_a_aoi_Intersect_Disso, dissolve_field=Dissolve_Field_s_, statistics_fields=[], multi_part="MULTI_PART", unsplit_lines="DISSOLVE_LINES")

    # Process: Add Field (2) (Add Field) (management)
    soilmu_a_aoi_Intersect_Disso_2_ = arcpy.management.AddField(in_table=soilmu_a_aoi_Intersect_Disso, field_name="Init_Soil_Moisture_WT", field_type="DOUBLE", field_precision=4, field_scale=None, field_length=None, field_alias="", field_is_nullable="NULLABLE", field_is_required="NON_REQUIRED", field_domain="")[0]

    # Process: Add Field (5) (Add Field) (management)
    soilmu_a_aoi_Intersect_Disso_4_ = arcpy.management.AddField(in_table=soilmu_a_aoi_Intersect_Disso_2_, field_name="Cap_Suction_WT", field_type="DOUBLE", field_precision=4, field_scale=None, field_length=None, field_alias="", field_is_nullable="NULLABLE", field_is_required="NON_REQUIRED", field_domain="")[0]

    # Process: Add Field (3) (Add Field) (management)
    soilmu_a_aoi_Intersect_Disso_7_ = arcpy.management.AddField(in_table=soilmu_a_aoi_Intersect_Disso_4_, field_name="HKWeight", field_type="DOUBLE", field_precision=4, field_scale=None, field_length=None, field_alias="", field_is_nullable="NULLABLE", field_is_required="NON_REQUIRED", field_domain="")[0]

    # Process: Join Field (2) (Join Field) (management)
    soilmu_a_aoi_Intersect_Disso_3_ = arcpy.management.JoinField(in_data=soilmu_a_aoi_Intersect_Disso_7_, in_field="UID_AE2S", join_table=RiverHills_AE2S, join_field="UID_AE2S", fields=["AreaSUBCAT"])[0]

    # Process: Calculate Field (3) (Calculate Field) (management)
    soilmu_a_aoi_Intersect_Disso_5_ = arcpy.management.CalculateField(in_table=soilmu_a_aoi_Intersect_Disso_3_, field="HKWeight", expression="[HK] * [Shape_Area]/ [AreaSUBCAT]", expression_type="VB", code_block="", field_type="TEXT")[0]

    # Process: Calculate Field (4) (Calculate Field) (management)
    soilmu_a_aoi_Intersect_Disso_9_ = arcpy.management.CalculateField(in_table=soilmu_a_aoi_Intersect_Disso_5_, field="Init_Soil_Moisture_WT", expression="[InitSoilMo] * [Shape_Area]/ [AreaSUBCAT]", expression_type="VB", code_block="", field_type="TEXT")[0]

    # Process: Calculate Field (5) (Calculate Field) (management)
    soilmu_a_aoi_Intersect_Disso_6_ = arcpy.management.CalculateField(in_table=soilmu_a_aoi_Intersect_Disso_9_, field="Cap_Suction_WT", expression="[CapSuction] * [Shape_Area]/ [AreaSUBCAT]", expression_type="VB", code_block="", field_type="TEXT")[0]

    # Process: Dissolve (3) (Dissolve) (management)
    soilmu_a_aoi_Intersect_Disso2 = "C:\\Users\\TMcStraw\\Documents\\ArcGIS\\Default.gdb\\soilmu_a_aoi_Intersect_Disso2"
    arcpy.management.Dissolve(in_features=soilmu_a_aoi_Intersect_Disso_6_, out_feature_class=soilmu_a_aoi_Intersect_Disso2, dissolve_field=["UID_AE2S"], statistics_fields=[["HKWeight", "SUM"], ["Init_Soil_Moisture_WT", "SUM"], ["Cap_Suction_WT", "SUM"]], multi_part="MULTI_PART", unsplit_lines="DISSOLVE_LINES")

    # Process: Alter Field (Alter Field) (management)
    soilmu_a_aoi_Intersect_Disso2_5_ = arcpy.management.AlterField(in_table=soilmu_a_aoi_Intersect_Disso2, field="SUM_Init_Soil_Moisture_WT", new_field_name="InitMoisWT", new_field_alias="", field_type="", field_length=8, field_is_nullable="NON_NULLABLE", clear_field_alias=False)[0]

    # Process: Alter Field (2) (Alter Field) (management)
    soilmu_a_aoi_Intersect_Disso2_3_ = arcpy.management.AlterField(in_table=soilmu_a_aoi_Intersect_Disso2_5_, field="SUM_HKWeight", new_field_name="HKWT", new_field_alias="", field_type="", field_length=8, field_is_nullable="NON_NULLABLE", clear_field_alias=False)[0]

    # Process: Alter Field (3) (Alter Field) (management)
    soilmu_a_aoi_Intersect_Disso2_4_ = arcpy.management.AlterField(in_table=soilmu_a_aoi_Intersect_Disso2_3_, field="SUM_Cap_Suction_WT", new_field_name="CapSuct_WT", new_field_alias="", field_type="", field_length=8, field_is_nullable="NON_NULLABLE", clear_field_alias=False)[0]

    # Process: Join Field (3) (Join Field) (management)
    subcatchments_lakes_model_cleaned_up_3_ = arcpy.management.JoinField(in_data=RiverHills_AE2S, in_field="UID_AE2S", join_table=soilmu_a_aoi_Intersect_Disso2_4_, join_field="UID_AE2S", fields=["HKWT", "InitMoisWT", "CapSuct_WT"])[0]

    # Process: Intersect (Intersect) (analysis)
    Impervious_Inter = "C:\\Users\\TMcStraw\\Documents\\ArcGIS\\Default.gdb\\Impervious_Inter"
    arcpy.analysis.Intersect(in_features=[[RiverHills_AE2S, ""], [RiverHillsImpervious, ""]], out_feature_class=Impervious_Inter, join_attributes="ALL", cluster_tolerance="", output_type="INPUT")

    # Process: Dissolve (Dissolve) (management)
    Impervious_Inter_Dissolve = "C:\\Users\\TMcStraw\\Documents\\ArcGIS\\Default.gdb\\Impervious_Inter_Dissolve"
    arcpy.management.Dissolve(in_features=Impervious_Inter, out_feature_class=Impervious_Inter_Dissolve, dissolve_field=Dissolve_Field_s_2_, statistics_fields=[], multi_part="MULTI_PART", unsplit_lines="DISSOLVE_LINES")

    # Process: Add Field (Add Field) (management)
    Impervious_Inter_Dissolve_6_ = arcpy.management.AddField(in_table=Impervious_Inter_Dissolve, field_name="Imp_Area", field_type="DOUBLE", field_precision=4, field_scale=None, field_length=None, field_alias="", field_is_nullable="NULLABLE", field_is_required="NON_REQUIRED", field_domain="")[0]

    # Process: Calculate Field (Calculate Field) (management)
    Impervious_Inter_Dissolve_3_ = arcpy.management.CalculateField(in_table=Impervious_Inter_Dissolve_6_, field="Imp_Area", expression=" [Shape_Area] * [Perc_Imp] /100", expression_type="VB", code_block="", field_type="TEXT")[0]

    # Process: Add Field (4) (Add Field) (management)
    Impervious_Inter_Dissolve_2_ = arcpy.management.AddField(in_table=Impervious_Inter_Dissolve_3_, field_name="Sub_P_Imp", field_type="DOUBLE", field_precision=4, field_scale=None, field_length=None, field_alias="", field_is_nullable="NULLABLE", field_is_required="NON_REQUIRED", field_domain="")[0]

    # Process: Join Field (Join Field) (management)
    Impervious_Inter_Dissolve_4_ = arcpy.management.JoinField(in_data=Impervious_Inter_Dissolve_2_, in_field="UID_AE2S", join_table=RiverHills_AE2S, join_field="UID_AE2S", fields=["AreaSUBCAT"])[0]

    # Process: Calculate Field (2) (Calculate Field) (management)
    Impervious_Inter_Dissolve_5_ = arcpy.management.CalculateField(in_table=Impervious_Inter_Dissolve_4_, field="Sub_P_Imp", expression="100*[Imp_Area]/ [AreaSUBCAT]", expression_type="VB", code_block="", field_type="TEXT")[0]

    # Process: Dissolve (4) (Dissolve) (management)
    Impervious_Inter_Dissolve_Di = "C:\\Users\\TMcStraw\\Documents\\ArcGIS\\Default.gdb\\Impervious_Inter_Dissolve_Di"
    arcpy.management.Dissolve(in_features=Impervious_Inter_Dissolve_5_, out_feature_class=Impervious_Inter_Dissolve_Di, dissolve_field=["UID_AE2S"], statistics_fields=[["Sub_P_Imp", "SUM"]], multi_part="MULTI_PART", unsplit_lines="DISSOLVE_LINES")

    # Process: Alter Field (4) (Alter Field) (management)
    Impervious_Inter_Dissolve_Di_3_ = arcpy.management.AlterField(in_table=Impervious_Inter_Dissolve_Di, field="SUM_Sub_P_Imp", new_field_name="PercentImp", new_field_alias="", field_type="", field_length=8, field_is_nullable="NON_NULLABLE", clear_field_alias=False)[0]

    # Process: Join Field (4) (Join Field) (management)
    Final_Subcatchment_Data = arcpy.management.JoinField(in_data=subcatchments_lakes_model_cleaned_up_3_, in_field="UID_AE2S", join_table=Impervious_Inter_Dissolve_Di_3_, join_field="UID_AE2S", fields=["PercentImp"])[0]

    # Process: Delete Field (Delete Field) (management)
    Final_Lakes_Subcatchments = arcpy.management.DeleteField(in_table=Final_Subcatchment_Data, drop_field=["ACRES", "area_sf", "Imp_Ac", "Imp_Per", "SUM_HKWeig", "SUM_Sub_P_", "SUM_Init_S", "SUM_Cap_Su"])[0]

if __name__ == '__main__':
    # Global Environment settings
    with arcpy.EnvManager(scratchWorkspace=r"C:\Users\DStock\OneDrive - AE2S\Documents\ArcGIS\Projects\MyProject5\MyProject5.gdb", workspace=r"C:\Users\DStock\OneDrive - AE2S\Documents\ArcGIS\Projects\MyProject5\MyProject5.gdb"):
        Model(*argv[1:])
